### ISSUE TITLE
Interactive webpage > summary statistics and data vis > Data visualisation

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical1#10]
Interactive webpage > summary statistics and data vis > Data visualisation > paragraph 10
1. edit sentence so it directs them to data-to-vis e.g. "If you are unsure of what plot would be best for your data, a good online resourse is data-to-vis which provides a flow chart that will help you make decisions."
2.  remove large graphic after paragraph

**Comment by rasanderson** [comment]
Changes made as suggested
