### ISSUE TITLE
Interactive webpage > summary statistics and data vis > Visualising individual variables

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical1#11]
Are the headings "Visualising individual variables" and "Visualising multiple variables" teh best headings? Should they be related more to continuous and categorical variables?

Interactive webpage > summary statistics and data vis > Visualising individual varaibles > paragraph 1
1. Need to state that we are using a histogram e.g. "We can use a the gf_historgram() function to produce a histogram which takes our numeric variable and cuts our data into bins and counts the frequency each value occurs in those bins."
2. what is the "summary statistics lesson"? Need to link more clearly to sections.

Interactive webpage > summary statistics and data vis > Visualising individual varaibles > paragraph 3
1. explanation needed for density plot e.g. "We can represent the distribution of values in another way by doing a density plot using gf_density() function. A density plot is similar to a histogram but the data are a smoothed version. Notice the y-axis has now changed and is showing a probability density instead but the interpetation of how those data are distributed is still the same."

Interactive webpage > summary statistics and data vis > Visualising individual varaibles > code box 1, 2 and 3 not working

Interactive webpage > summary statistics and data vis > Visualising individual varaibles > paragraph 4
1. Need to state that why we are using a bar chart and move section to next page which includes bar charts and box plots e.g. "A bar chart is a good way to look at the numeric values for categorical data. Each group is represented by a bar and there are gaps between bars which is a key distinction between a bar chart and histogram."

**Comment by rasanderson** [comment]
Information on histograms and density plots updated, plus link to correct practical session. Separate page created for bar charts. Code boxes now seem to run OK. Shiny website name now prefixed with NES2303 for ease of location in shiny server, but cross-references on Canvas will need updating.
