### ISSUE TITLE
Interactive webpage > summary statistics and data vis > Multiple individual variables

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical1#12]
Interactive webpage > summary statistics and data vis > Multiple individual variables > whole page
1. The bar chart information should all be on one page and include boxplots. Needs to build from simple bar chart to more complicated with error bars then to boxplots. The scatterplot information should be on its on own page. Need to make the distinction among figures that look at relationships between variables which have continuous data and differences between variables using categorical data. This should then map onto the data exploration for the different data sets for the statistical analysis.

Interactive webpage > summary statistics and data vis > Multiple individual variables > paragraph 4
1. Be specifc rather than using "this" e.g. "By plotting proportional data, we can now see that nearly 50% of these penguin data have come from Biscoe Island. This is because the Biscoe Island bar is nearly at 0.5 which is 50%."

Interactive webpage > summary statistics and data vis > Multiple individual variables > paragraph 5
1. Need to state why we are using a scatterplot e.g. "When we have two or more variables that are quantitative data, we are often interested in the relationship between those variables. We can plot quantitative data (count data or measurements) together using the gf_point() function to get a scatterplot. In our pengiun data set, they have measured bill length and bill depth. We can look at the relationship between these two variables by plotting bill_depth_mm on the y-axis and bill_length_mm on the x-axis."
2. move "Can you modify the below code to

Colour the points according to Species
Size the points according to body mass" to below plot

Interactive webpage > summary statistics and data vis > Multiple individual variables > paragraph 6
1. edit paragraph to add the why we are doing it e.g. "We can see from the scatterplot that there is a lot data here but the plotting doesn't distinguish between the species so we don't know if the relationship between bill_depth_mm and bill_length_mm is the same for each species. We can produce a more informative informative plot that clearly shows the trends within each species by adding colour."

Interactive webpage > summary statistics and data vis > Multiple individual variables > new code box
1. add new code box here for plotting figure in colour to allow students to see the difference and remove "size = ~body_mass_g," from the code e.g. 
"# colour by species, size by body_mass 
gf_point(bill_depth_mm ~ bill_length_mm, colour = ~species,  data= penguins)"

Interactive webpage > summary statistics and data vis > Multiple individual variables > paragraph 7
1. edit paragraph to add the why we are doing it e.g. "You have just created a plot which include colour and we can now see that there are differences in the relationship between  bill_depth_mm and bill_length_mm for the different species. But we can make this figure tider, more professional looking and get it "publication" ready."

Interactive webpage > summary statistics and data vis > Multiple individual variables > code box 4
1. change gf_theme(theme_minimal()) to gf_theme(theme_classic()) so that the figure includes axes and removes the grey lines 

Interactive webpage > summary statistics and data vis > Multiple individual variables > paragraph 13
1. remove "plotting measurements through time?" or add an example

Interactive webpage > summary statistics and data vis > Multiple individual variables > paragraph 15
1. Need to state why we are using a boxplot e.g. "We can use a boxplot to look at the differences in the groups within our categorical variable. Boxplots give us more insight into our data and depending on sample size are better to use than bar charts."

Interactive webpage > summary statistics and data vis > Multiple individual variables > paragraph 16
1. Edit first sentence e.g. "We will go into more depth on how to interpet boxplots in later sessions but for now we can see that Gentto penguins are generally more heavier that the other species."

Interactive webpage > summary statistics and data vis > Multiple individual variables > paragraph 17
1. Edit paragarph 17 e.g. "We can now see our data points"

**Comment by rasanderson** [comment]
Most changes now completed for this issue.
