### ISSUE TITLE
Interactive webpage > Understanding variation in your data > Measures of central tendency

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical1#15]
Interactive webpage > Understanding variation in your data > Measures of central tendency  >paragraph 1
1. Need a comment on why it is important to choose the correct measure of central tendancy. Add a sentence at the end of the paragraph. e.g. "We need to understand the difference between how a mean and a median are calculated and what their values represent."
2. spelling error "which they are calculate" change to "calculate"
Interactive webpage > Understanding variation in your data > Measures of central tendency > paragraph 2
1. Remove "this" adn repalce with "The mean"

Interactive webpage > Understanding variation in your data > Measures of central tendency > figure 1 and 2
1. Can you put vertical lines on these plots to show the positions of the mean and the median. 
2. Can we add horizontal boxplots to this section to show how a boxplot may change when data are skewed.

**Comment by willdkreid** [comment]
Interactive webpage > Understanding variation in your data > Measures of central tendency > paragraph 2
1. Remove "this" adn repalce with "The mean"

Interactive webpage > Understanding variation in your data > Measures of central tendency > figure 1 and 2
1. Can you put vertical lines on these plots to show the positions of the mean and the median. 
2. Can we add horizontal boxplots to this section to show how a boxplot may change when data are skewed.

**Comment by rasanderson** [comment]
All changes made - horizontal boxplots added with ggside package
