### ISSUE TITLE
Interactive webpage > Understanding variation in your data > The SS

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical1#18]
Interactive webpage > Understanding variation in your data > The SS
1. edit first sentence because it sounds weird and a lot of students won't understand what the SS were and lacks context for why we interested in the sums of squares

Interactive webpage > Understanding variation in your data > The SS > paragarph 1

2nd sentence change "be" to "by"

**Comment by willdkreid** [comment]
Interactive webpage > Understanding variation in your data > The SS > paragarph 1
1. 2nd sentence change "be" to "by"

**Comment by rasanderson** [comment]
First paragraph of SS section improved and typos corrected.
