### ISSUE TITLE
Interactive webpage > Understanding variation in your data > Problems with SS

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical1#19]
Interactive webpage > Understanding variation in your data > Problems with SS > code box 1
1. edit the code box so the code is there for them - at this point they are still learning the basic functions mean(), median(), min(), max() etc

Interactive webpage > Understanding variation in your data > Problems with SS > paragraph 4
1. SS is 64 not 62

**Comment by rasanderson** [comment]
Code moved from solution into main code box, and typo corrected.
