### ISSUE TITLE
Interactive webpage > Understanding variation in your data > Variance: correcting SS for the number of records

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical1#20]
Interactive webpage > Understanding variation in your data > Variance: correcting SS for the number of records > paragraph 2
1. remove "therefore"

Interactive webpage > Understanding variation in your data > Variance: correcting SS for the number of records > paragraph 5
1. full stopmissing after 30.0

**Comment by rasanderson** [comment]
Typos corrected
