### ISSUE TITLE
Interactive webpage > Understanding variation in your data > Calculating the variance (SS corrected for number of observations)

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical1#21]
Interactive webpage > Understanding variation in your data > Calculating the variance (SS corrected for number of observations) > paragraph 6
1. You need to introduce the caterpillars and crop growth data sets; this is first time they have encountered them. They will need to know the different variable names.

Interactive webpage > Understanding variation in your data > Calculating the variance (SS corrected for number of observations) > code box 1
1. Give them some code and ask them to edit it. They should be able to do this once they know the variable names what they are.
e.g # Overall variance for each column (tanin, growth) for caterpillers # data set
# tanin

# growth

# Overall variance for crop yield

# Variance for each soil type

**Comment by rasanderson** [comment]
Changes made as requested to resolve issue.
