### ISSUE TITLE
Interactive webpage > Understanding variation in your data > Accuracy and precision

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical1#22]
Interactive webpage > Understanding variation in your data > Accuracy and precision > paragraph 1
1. remove "these" from first sentence and replace with "accuracy and precision"; not sure tradeoff makes sense here.
2. First sentence needs edited to that there is conceptual link between SD and SE.

Interactive webpage > Understanding variation in your data > Accuracy and precision > paragraph 5
1. is "accuracy and precision"

Interactive webpage > Understanding variation in your data > Accuracy and precision > paragraph 7
1. needs final sentence linking this page to next page

**Comment by rasanderson** [comment]
Not entirely sure what was being referred to in Paragraph 5 (though I may have miscounted paragraph numbers due to pictures and bullet points).

**Comment by rasanderson** [comment]
Other changes implemented as requested so closing for now.
