### ISSUE TITLE
Interactive webpage > Understanding variation in your data > How to measure accuracy and precision

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical1#23]
Interactive webpage > Understanding variation in your data > How to measure accuracy and precision >  paragraph 5
1. State why it is generally better to use standard error over standard deviation e.g. "Standard error is usually preferred to standard deviation when presenting summary statistics in graphs or tables, as it corrects for sample size."

**Comment by rasanderson** [comment]
Text updated as SD not really a measure of accuracy (can only be done properly with e.g. a reference standard etc.)

**Comment by rasanderson** [comment]
Other text updated to resolve issue.
