### ISSUE TITLE
Interactive webpage > Understanding variation in your data > Confidence intervals

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical1#24]
Interactive webpage > Understanding variation in your data > Confidence intervals > whole page
1. Confidence intervals need better explanation, when are they used and how to interpret them.

Interactive webpage > Understanding variation in your data > Confidence intervals > code box
1. Turn the code in the box into something that they can run but give it a known data set.

Interactive webpage > Understanding variation in your data > Confidence intervals > new paragraph after 4
1. Interpret the output and explain that there is a 95% probablity that our parameter estimate will be between the two values

**Comment by rasanderson** [comment]
Changes made, with better explanation and examples
