### ISSUE TITLE
Practical 1 > Aims and objectives of Practical 1

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical1#26]
Practical 1 > Aims and objectives of Practical 1 > paragraph 1 bullet point 2
1. remove "of"

Practical 1 > Aims and objectives of Practical 1 > new paragraph after 2
1. After data paragraph add a new paragraph saying which libraries we will be using

**Comment by rasanderson** [comment]
Minor changes made as suggested.
