### ISSUE TITLE
Practical 1 > 2 Start RStudio, open your BIO2020 project, create R script

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical1#27]
Practical 1 > 2 Start RStudio, open your BIO2020 project, create R script > paragraph 2
1. change bio2020 to mosaic

Practical 1 > 2 Start RStudio, open your BIO2020 project, create R script > code box 1
1. change to library mosaic

**Comment by rasanderson** [comment]
NES2303 now replaces BIO2020 (except in some screenshots). Other changes made as suggested.
