### ISSUE TITLE
Practical 1 > 5.2 Calculate the variance and standard deviation for each diet

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical1#30]
Practical 1 > 5.2 Calculate the variance and standard deviation for each diet > paragraph 1
- remove info regarding Teams if not using it this year or update the sentence if you plan to. At the moment it seems like the students will be working from home rather than in-person

Practical 1 > 5.2 Calculate the variance and standard deviation for each diet > code b0x 3
- spelling error "calculating" not "calcualating" `# calcualating variance for each group`

**Comment by rasanderson** [comment]
Changes made as requested
