### ISSUE TITLE
Practical 1 > 5.3 Calculate standard error

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical1#31]
Practical 1 > 5.3 Calculate standard error > paragraph 4

- It would be useful to bind the fav_dat and chicken_se together. e.g. "Once you have calculate chick_se, then you can use cbind to add this new variable to your fav_dat data frame. "

Practical 1 > 5.3 Calculate standard error > code box 1

- add the cbind function
`# bind chick_se to fav_dat
fav_dat <- cbind(fav_dat, chick_se)`

`# inspect the data frame to see the extra column
favt_dat`

**Comment by willdkreid** [comment]
Practical 1 > 5.3 Calculate standard error > code box 1

add the cbind function `# bind chick_se to fav_dat
fav_dat <- cbind(fav_dat, chick_se)
# inspect the data frame to see the extra column
favt_dat`

**Comment by willdkreid** [comment]
Sorry keep making a mistake "#" in the issue:

add the cbind function 
# bind chick_se to fav_dat
fav_dat <- cbind(fav_dat, chick_se)
# inspect the data frame to see the extra column
favt_dat

**Comment by rasanderson** [comment]
SE column added with cbind, and explains why fav_dat quite complex so we create diet_stats table.
