### ISSUE TITLE
Practical 1 > 5.4 Assemble all your summary statistics into a new table

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical1#32]
Practical 1 > 5.4 Assemble all your summary statistics into a new table > code box 1
- The summary table doesn't have a column with the categorical variable in it. It would be useful to add this because it will help with plotting.

`diet_stats$diet <- row.names(diet_stats)`

**Comment by rasanderson** [comment]
Changes made as suggested
