### ISSUE TITLE
Practical 1 > 6.2.3 Chain plot commands to improve graphs

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical1#33]
Practical 1 > 6.2.3 Chain plot commands to improve graphs > paragraph 3

- remove theme_minimal and just keep them focused on using theme_classic

Practical 1 > 6.2.3 Chain plot commands to improve graphs > new paragraph

- need to add how to put error bars in this section and remove all the bivalve bit. It will need to use the fav_dat or the diet_stats data set which the standard error has been added to. e.g. "Building up graphs from simple to more complex ones like this by “chaining” commands together is always more reliable than trying to write the whole graph first. We can practice this again by plotting mean chick weight against experimental diet and this time add standard error bars to the plot. We will need to use the function `gf_col` because we are using the means and standard errors which you created earlier and saved in `fav_dat`. Once you have completed this, remember to save your practical1.R script and keep saving it regularly as you go through."

Practical 1 > 6.2.3 Chain plot commands to improve graphs > new code box
`# add error bars
gf_col(mean ~ Diet, data = fav_dat) %>%  # Plot bar chart THEN
  gf_labs( y = "Mean Chick Weight (kg) +/- SE", x = "Experimental Diet") %>% # Modify axis labels THEN
  gf_errorbar((mean - chick_se) + (mean + chick_se) ~ Diet, width = 0.2) %>%
  gf_theme(theme_classic())`

**Comment by rasanderson** [comment]
Issue #33 resolved with barchart +/- SE example added
