### ISSUE TITLE
Practical 1 > 6.3.1 Boxplots

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical1#34]
Practical 1 > 6.3.1 Boxplots > paragraph 2

- need to highlight diet is the explanatory e.g. ""We now need two variables, i.e. the y-axis (vertical axis) “response” variable of chick weight vs the x-axis (horizontal) of diet type which is the "explanatory" variable."

Practical 1 > 6.3.1 Boxplots > code box 1

- add theme_classic
-`# Display boxplot of final chick weight for each diet
gf_boxplot(weight~diet, data = diet_dat) %>%
gf_theme(theme_classic())`

**Comment by rasanderson** [comment]
Issue #34 resolved with boxplot info improved
