### ISSUE TITLE
Interactive webpage > summary statistics and data vis > checking data

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical1#5]
Interactive webpage > summary statistics and data vis > checking data > paragraph 2
1. palmer needs a capital > Palmer

Interactive webpage > summary statistics and data vis > checking data > code box 1
1. remove # from before names() and dim() and put penguins in () because instructions aren't clear what the student needs to do.

Interactive webpage > summary statistics and data vis > checking data > paragraph 7
1. no explanation of str() function and what the results mean e.g. what is a factor, num, int etc… T

**Comment by rasanderson** [comment]
Changes made as requested
