### ISSUE TITLE
Interactive webpage > summary statistics and data vis > Calculating summary statistics

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical1#6]
Interactive webpage > summary statistics and data vis > Calculating summary statistics > code box 2
1. keep code let them run it themselves

Interactive webpage > summary statistics and data vis > Calculating summary statistics > question box
1. question not clear about what it is asking - just state there are NAs

Interactive webpage > summary statistics and data vis > Calculating summary statistics > code box 3
1. keep code but let run it themselves

**Comment by rasanderson** [comment]
All changes made. Added additional box template diagram to aid understanding of format for single variable means.
