### ISSUE TITLE
Interactive webpage > summary statistics and data vis > Using the template for simple statistics

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical1#8]
Interactive webpage > summary statistics and data vis >Using the template for simple statistics > paragraph 1
1. change "are" to "our"

Interactive webpage > summary statistics and data vis >Using the template for simple statistics > paragraph 7
1. state we will use favstats() in the practical so they know this is going to be important e.g. "We will use favstats() in Practical 1 so you will see how it works."

**Comment by rasanderson** [comment]
Changes made as suggested
