### ISSUE TITLE
Interactive webpage > summary statistics and data vis > Always plot your data

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical1#9]
Interactive webpage > summary statistics and data vis > Always plot your data > paragraph 2
1. Not defined what a "character" variable is. Link back to str() function on Checking data page?

Interactive webpage > summary statistics and data vis > Always plot your data > code box 2
1. "# mean and sd =" remove sd because not being calculated change to # mean of x values in each group

Interactive webpage > summary statistics and data vis > Always plot your data > code box 3
1. add comment above code e.g. # mean of y values in each group

Interactive webpage > summary statistics and data vis > Always plot your data > code box 4
1. add comment above code e.g. # sd of x values in each group

Interactive webpage > summary statistics and data vis > Always plot your data > code box 5
1. add comment above code e.g. # sd of y values in each group

Interactive webpage > summary statistics and data vis > Always plot your data > paragraph 5

Not clear what "hint: remember forumla" is referring too - should be above code boxes?
Interactive webpage > summary statistics and data vis > Always plot your data > paragraph 7

Need to state that gf_point is the plotting function for a scatterplot and remove "code" e.g. "Let us plot all the x and y values in one scatterplot using the gf_point() function. We will use the option = ~colour to colour the points by dataset."

**Comment by willdkreid** [comment]
Interactive webpage > summary statistics and data vis > Always plot your data > paragraph 5
1. Not clear what "hint: remember forumla" is referring too - should be above code boxes?

Interactive webpage > summary statistics and data vis > Always plot your data > paragraph 7
1. Need to state that gf_point is the plotting function for a scatterplot and remove "code" e.g. "Let us plot all the x and y values in one scatterplot using the gf_point() function. We will use the option = ~colour to colour the points by dataset."

**Comment by rasanderson** [comment]
All changes made as suggested.
